site_name: My Docs
site_description: "Technical documentation for me."
site_author: 'Kazuki Yokoi'
docs_dir: docs/
repo_name: 'k-yokoi/doc'
repo_url: 'https://github.com/k-yokoi/doc'
theme:
  name: 'material'
  language: ja
  icon:
    repo: fontawesome/brands/github